color0 #52443c
color1 #ffb4ab
color2 #ffb787
color3 #e5bfa8
color4 #caca93
color5 #ffb787
color6 #e5bfa8
color7 #f0dfd7
color8 #9f8d83
color9 #ffb4ab
color10 #ffb787
color11 #e5bfa8
color12 #caca93
color13 #ffb787
color14 #e5bfa8
color15 #f0dfd7

cursor                #f0dfd7
cursor_text_color     #19120d
background            #19120d
foreground            #f0dfd7
selection_foreground  #d7c3b8
selection_background  #52443c
active_border_color   #ffb787
inactive_border_color #52443c
url_color             #ffb787

active_tab_foreground   #512400
active_tab_background   #ffb787
inactive_tab_foreground #d7c3b8
inactive_tab_background #52443c
cursor_trail_color      #d7c3b8
