# Noctalia theme for snappy-switcher

[colors]
background = #19120daa
card_bg = #261e19aa
card_selected =  #3d332dff
text_color = #ffdcc7dd
subtext_color =  #ffdcc7cc
border_color =  #9f8d83ff
bundle_bg = #5b4130ff
badge_bg =  #e5bfa8aa
badge_text_color = #422b1baa
badge_bg_selected = #e5bfa8cc
badge_text_color_selected = #422b1bff